services:
  postgres:
    image: postgres:16-alpine
    container_name: livinova-postgres
    environment:
      POSTGRES_DB: Livinova
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "11111111"
    ports:
      - "5432:5432"
    volumes:
      - livinova_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d Livinova"]
      interval: 5s
      timeout: 5s
      retries: 20

  redis:
    image: redis:7-alpine
    container_name: livinova-redis
    ports:
      - "6379:6379"
    volumes:
      - livinova_redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  livinova_postgres_data:
  livinova_redis_data:
